**EXAMPLE FILE**

	adjective	verb	noun	noun	pn;
	cm	verb	adjective	pnoun	pn;
	verb_aux	SYM	particle	noun	pn;
	pnoun	pnoun	noun	noun	pn;
	demonstrative	noun	adjective	noun	pn;
	noun	verb	quantifier	adjective	pn;
	cardinal	noun	verb	verb_aux	pn;
	verb	noun	adjective	neg	pn;
	SYM	SYM	noun	cm	pn;
	verb_aux	verb_aux	pnoun	cm	pn;
	verb	verb_aux	pnoun	pnoun	pn;
	noun	cm	adjective	noun	pn;
	noun	verb	adjective	noun	pn;
	noun	verb	pnoun	pnoun	pn;
	pnoun	pnoun	noun	cm	pn;
	noun	verb	noun	cm	pn;
	pnoun	cm	cardinal	noun	pn;
	noun	cm	adjective	noun	pn;
	verb	verb_aux	particle	verb	pn;
	verb	verb_aux	pnoun	cm	pn;
	verb	verb_aux	adjective	noun	pn;
	verb	verb_aux	pn	noun	pn;
	verb_aux	verb_aux	adjective	neg	pn;
	noun	verb	conj	noun	pn;
	verb	verb_aux	conj	adjective	pn;
	neg	verb	noun	cm	pn;
	verb_aux	verb_aux	pnoun	conj	demonstrative;
