**EXAMPLE FILE**

	verb	verb_aux	adjective	noun	pn;
	verb	verb_aux	demonstrative	noun	pn;
	pnoun	cm	noun	cm	pn;
	verb	verb_aux	demonstrative	quantifier	pn;
	pnoun	cm	cm	adjective	pn;
	noun	verb	pnoun	pnoun	pn;
	verb_aux	verb_aux	demonstrative	pnoun	pn;
	pn	adverb	verb	pn	adverb;
	adverb	verb	quantifier	noun	pn;
	verb	verb_aux	pnoun	pnoun	pn;
	verb	SYM	particle	adjective	pn;
	SYM	noun	pnoun	pnoun	pn;
	SYM	conj	pnoun	noun	pn;
	verb	conj	pn	cm	pn;
	verb	verb_aux	noun	verb	pn;
	pn	noun	noun	cm	pn;
	particle	conj	pn	demonstrative	pn;
	verb	conj	cm	demonstrative	pn;
	SYM	pn	noun	cm	pn;
	SYM	adjective	pnoun	verb	pn;
	particle	verb	cardinal	noun	conj;
	verb_aux	conj	pnoun	noun	pn;
	verb	conj	pn	noun	pn;
	noun	verb	pn	noun	pn;
	verb_aux	verb_aux	pnoun	cm	pn;
	SYM	SYM	noun	cm	pn;
	verb_aux	verb_aux	noun	cm	pn;
